apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: client
    app.kubernetes.io/name: spring-sensors-client
    app.kubernetes.io/part-of: spring-sensors
  name: spring-sensors-client
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: client
      app.kubernetes.io/name: spring-sensors-client
      app.kubernetes.io/part-of: spring-sensors
  template:
    metadata:
      labels:
        app.kubernetes.io/component: client
        app.kubernetes.io/name: spring-sensors-client
        app.kubernetes.io/part-of: spring-sensors
    spec:
      containers:
      - env:
        - name: SERVICE_BINDING_ROOT
          value: /bindings
        - name: PORT
          value: "8080"
        name: spring-sensors-client
        image: REGISTRY/PROJECT/spring-sensors-client:latest
        ports:
        - containerPort: 8080
          name: sensor-port
          protocol: TCP
        volumeMounts:
        - mountPath: /bindings/rmq
          name: client-binding-rmq-1
          readOnly: true
      volumes:
      - name: client-binding-rmq-1
        projected:
          defaultMode: 420
          sources:
          - secret:
              name: rmq-1-default-user
