apiVersion: v1
kind: Service
metadata:
  name: spring-sensors-svc
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: spring-sensors-client
  type: LoadBalancer
